import React from "react";
import "./../../styles/ExperienceStyles/xfive-information.css";

const XFiveInformation = () => {
    return (
        <div className="scroll-container">
            <div className="scroll-item">Элемент 2</div>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque necessitatibus magnam architecto dolore corporis, cumque harum voluptate facere laboriosam ab cupiditate libero totam optio obcaecati nisi alias! Voluptas sint ab ipsam harum esse fuga dolorem. Debitis perspiciatis necessitatibus deserunt nobis fugit atque praesentium aperiam, culpa quae nam numquam odio error obcaecati dolor in consequuntur inventore voluptatum itaque perferendis reprehenderit tempora eveniet. Vero ratione dicta fugiat aperiam iure tempora veritatis laudantium qui unde, magnam nostrum vitae nam. Maxime labore nobis, beatae debitis quis voluptatibus aspernatur? Recusandae nostrum hic nemo ducimus minima cupiditate sequi aliquid explicabo ratione. Est enim iste atque debitis.</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque necessitatibus magnam architecto dolore corporis, cumque harum voluptate facere laboriosam ab cupiditate libero totam optio obcaecati nisi alias! Voluptas sint ab ipsam harum esse fuga dolorem. Debitis perspiciatis necessitatibus deserunt nobis fugit atque praesentium aperiam, culpa quae nam numquam odio error obcaecati dolor in consequuntur inventore voluptatum itaque perferendis reprehenderit tempora eveniet. Vero ratione dicta fugiat aperiam iure tempora veritatis laudantium qui unde, magnam nostrum vitae nam. Maxime labore nobis, beatae debitis quis voluptatibus aspernatur? Recusandae nostrum hic nemo ducimus minima cupiditate sequi aliquid explicabo ratione. Est enim iste atque debitis.</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque necessitatibus magnam architecto dolore corporis, cumque harum voluptate facere laboriosam ab cupiditate libero totam optio obcaecati nisi alias! Voluptas sint ab ipsam harum esse fuga dolorem. Debitis perspiciatis necessitatibus deserunt nobis fugit atque praesentium aperiam, culpa quae nam numquam odio error obcaecati dolor in consequuntur inventore voluptatum itaque perferendis reprehenderit tempora eveniet. Vero ratione dicta fugiat aperiam iure tempora veritatis laudantium qui unde, magnam nostrum vitae nam. Maxime labore nobis, beatae debitis quis voluptatibus aspernatur? Recusandae nostrum hic nemo ducimus minima cupiditate sequi aliquid explicabo ratione. Est enim iste atque debitis.</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque necessitatibus magnam architecto dolore corporis, cumque harum voluptate facere laboriosam ab cupiditate libero totam optio obcaecati nisi alias! Voluptas sint ab ipsam harum esse fuga dolorem. Debitis perspiciatis necessitatibus deserunt nobis fugit atque praesentium aperiam, culpa quae nam numquam odio error obcaecati dolor in consequuntur inventore voluptatum itaque perferendis reprehenderit tempora eveniet. Vero ratione dicta fugiat aperiam iure tempora veritatis laudantium qui unde, magnam nostrum vitae nam. Maxime labore nobis, beatae debitis quis voluptatibus aspernatur? Recusandae nostrum hic nemo ducimus minima cupiditate sequi aliquid explicabo ratione. Est enim iste atque debitis.</p>
        </div>
    );
}

export default XFiveInformation;